name: Compilar y Desplegar en cPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 🚀 Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Descargando el código fuente
      uses: actions/checkout@v4
      
    - name: ⚙️ Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'
        
    - name: 📦 Instalar dependencias
      run: npm install
      
    - name: 🛠️ Generar el Build
      run: npm run build
      
    - name: 📂 Sincronizando archivos por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/ # 🔥 MUY IMPORTANTE: Solo sube la carpeta compilada
        server-dir: /